name: Build and upload to PyPI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_and_publish:
    runs-on: ubuntu-22.04
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.3"

      - name: Build the wheel and sdist
        run: uv build

      - name: Publish to TestPyPI
        run: uv publish --token ${{ secrets.TEST_PYPI_TOKEN }} --index testpypi

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
